#:schema node_modules/wrangler/config-schema.json
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]
name = "flat-cms"
pages_build_output_dir = "./dist"

# Automatically place your workloads in an optimal location to minimize latency.
# If you are running back-end logic in a Pages Function, running it closer to your back-end infrastructure
# rather than the end user may result in better performance.
# Docs: https://developers.cloudflare.com/pages/functions/smart-placement/#smart-placement
# [placement]
# mode = "smart"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Docs:
# - https://developers.cloudflare.com/pages/functions/bindings/#environment-variables
# Note: Use secrets to store sensitive data.
# - https://developers.cloudflare.com/pages/functions/bindings/#secrets
[vars]
AUTH_SECRET = "KHjom6kJ9yMMh1HZXIETeS1s1oAcm94JzkbgpaWvqLyz9ZiA4xk5PGm+0EI="
AUTH_TRUST_HOST = "true"
GITHUB_APPID = "1068394"
GITHUB_CLIENT_ID = "Iv23lijJuNWmt6gYodDT"
GITHUB_CLIENT_SECRET = "31f47b8a3e9a245b43991c127e6de06cf4a10e78"
GITHUB_PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDgQZ0f4cNF232r
H87F/gKJy8Xp4Eoof63/zBBu+X6uNVI3qyymX9AcPfV/HUouSODRVr8Jk6x/AhAO
7n52uS4pOQeeLXfcFtT6R29G4lH+4TKdR//G1TWyxrskia/J7AS5OUGE594NHZ0e
HV9HpUY1Vmgyp0zMlvJU8EnIxE7cJMJEsekLGWg0bjQ6tVXz5LwlWYTRLLarglpH
Uym9DUHicwyLypbo1butfkUahEknGy5AHs7EQvSimNngjWGB7iCJlSXXEkWPYYRq
c6qtqAcoSGffbE0h2ctMjf3bc4/raOH3uTjS1Yfe3C5p52vIgFJ23rcaKL2hInH+
0skxP0jPAgMBAAECggEARfdSrWLDiOUNFTnMSmuQoStJaUmH+ZC0Wc1yBx2iT3nl
V+b4/EOCa31NPcaGoWAtfEKjQbqoI8wh9HamUCZAZ64aWVh4P9uDwT5OUoBD8tCR
+Q5Al+lnYoqsUp7+kHIpmxxo+61X0yG9JmslkfXXrMZzpfIafO5PVv7NFm1g6T+d
MK8P7c1wJyohJ5lw9E9fXbRnIAhEYg6QJMxpzhNeEpQzTR6eUh+bjT8akluyIF2Q
FE1JTpnZ8DkhaYlXVVkrdmUn5YiZwYXV+IG0/O/vNQaG9BYFEgMh35CxUShrOksY
UkkiiBk3C8+H7vZV2Ix9lL5ZKNyQtgmDlqgBWCC2MQKBgQDzqsyXrdJeTcDmQ9y1
2kIu4b768vVDklZ41Rtl2B+8zDxWxeX/1MYbQkXzDkpQVUeQd+vd1qeR+DXGDrhO
uh3PC8+HKTEbtZcvDcaKMld+YRmzV1Ey6UXr78JH9Zmt4m36gPQHNNZMHf/wIsfW
MRUMY+kbrhb2Tied8ZVaelAT+QKBgQDrm06xRUWP1ZiN+7i6xW7FvdqBmWnQJOp/
bwfeNJ3W8cBlWhhhbsIRdx5UtXIebfHPNp9SFguPNh+yyt/K0YXpzf5VI7z9M8co
36D54u65kdZZwLKIL29z59Z0TnkVrABRVGv2/qse/oPUOcxtgNp9IoXabv12tjMJ
PDu3mvnlBwKBgQDiDR8WzBQwlpORS32zW5MwqQ8jAkiU8mq0WIe9WN5AqXyEx71T
NJLA8R+xmB1LH4JvvUEdIal9mrZQUpGbv8Att3hEnOtJGJLz/SSmSoOu4+gS37ud
rpnGgzxKw8dZcIm07vL0yIjSPraUkb+wrwIm5313x27X+7N3LIrxUC2ACQKBgF7x
xTJ2weOGpeWBrR3G9i7FpUpYsmVomv8jlT4cYgb+gRPWzMBmy9oR8K0eOZC9qZZh
Yq7Hp3zcyMVaL/khmh9wHa/dqQk4VmfIRqysoJszg/fDSa7LvtQsdyWDghQTrkUY
CjIMypTA6AscB5+RL3sB8ILn+0hdgA+WsFH7J/z9AoGAMu+fpxeCg7l4t+C1FGQu
rSA8YiQG8sZ3xiIxRBaBRCMI3NAgZCZSrqVNtZ1zWxEyUsT6HC3pSn55zqPQsCkM
jaDd2LMSxr+BIp0Gn4OO3nwY26MRDFtHzhvx1SlSiXwsmMl77xdM8NAqIWf0xror
hoq/C+pwa69QC0/MKyy/FG0=
-----END PRIVATE KEY-----"""
LEMON_SQUEEZY_API_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5NGQ1OWNlZi1kYmI4LTRlYTUtYjE3OC1kMjU0MGZjZDY5MTkiLCJqdGkiOiI2OGE3NzVhMDIzMDIwNzY4M2QxNGYwZWM4YzRlM2YwZTE5MjRiOTU2MGRjODdlMWVmYjMyZTE2NDlmYTNjMTA3Nzg1ZmUxMmU5MDBmMTJjYiIsImlhdCI6MTcyODE2NTI1OC45MzUyNTUsIm5iZiI6MTcyODE2NTI1OC45MzUyNTgsImV4cCI6MjA0MzY5ODA1OC44OTU5OTksInN1YiI6IjM0MTE5NTEiLCJzY29wZXMiOltdfQ.Dmg8bs5enfKambjWfTFZ0t3o7fFDrXA9b0bvqpxuC8S9CWrqtS8uvs2RGvGOdcZ1ytg57KVVPICox5kG79F1D-ogHBIe1hquY50ebe4NegLzDfsknbHGgxA209PqKA_go89Di9VfESz3hIbaegLzzpdn56Y4IJJ_95GgMiWlOKvwcgZPjUTg_JYawZVRsAjMKsTYQcx77ZjQCDlnsm5cQ4X9a5ifgiZBlUGGzyGm92Q6JVBXT_tHrk9ZcG_c1LZeuJuQ1b6BOAzSsJdJNfon0mlFRLtyofQKC6OehG4B-dKCQcvlF-wZbAODMRGQXmXa1nOKcEU-jN9Z0VjaImZq03P-kSgZSe2-TxRellenDkbS4RBxZ_ASBcU2_nXp4gYLihZqrFfBeSoP9oqmmN4znZytbNylKyPDn8cKD3wxRvEkufRSWzwsk6qmPFIZku0IIaqAhhBlCDbR_jGTpLhvXShMgGyAZI6ZRPLgC1uQug4x3eOmr-R-EVU6mJbTIetv"
LEMON_SQUEEZY_SIGNING_SECRET = "hOQS//kBtPFIMZlW6hANW5sqKQ1EBJ38eD6ji6ciD6/3aVGST9Y7GRNXXNo="
LEMON_SQUEEZY_STORE_ID = "125811"
[[d1_databases]]
binding = "DB"
database_id = "d23e8a5a-a2d7-4092-a556-b9e7c7b421c1"
database_name = "flatcms"
migrations_dir = "./drizzle/"

# MY_VARIABLE = "production_value"

# Bind the Workers AI model catalog. Run machine learning models, powered by serverless GPUs, on Cloudflare’s global network
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#workers-ai
# [ai]
# binding = "AI"

# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#d1-databases

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
# [[durable_objects.bindings]]
# name = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"
# script_name = 'my-durable-object'

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#kv-namespaces
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Bind a Queue producer. Use this binding to schedule an arbitrary task that may be processed later by a Queue consumer.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#queue-producers
# [[queues.producers]]
# binding = "MY_QUEUE"
# queue = "my-queue"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#r2-buckets
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# Bind another Worker service. Use this binding to call another Worker without network overhead.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#service-bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"

# To use different bindings for preview and production environments, follow the examples below.
# When using environment-specific overrides for bindings, ALL bindings must be specified on a per-environment basis.
# Docs: https://developers.cloudflare.com/pages/functions/wrangler-configuration#environment-specific-overrides

######## PREVIEW environment config ########

# [env.preview.vars]
# API_KEY = "xyz789"

# [[env.preview.kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "<PREVIEW_NAMESPACE_ID>"

######## PRODUCTION environment config ########

# [env.production.vars]
# API_KEY = "abc123"

# [[env.production.kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "<PRODUCTION_NAMESPACE_ID>"
