#:schema node_modules/wrangler/config-schema.json
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]
name = "flat-cms"
pages_build_output_dir = "./dist"

# Automatically place your workloads in an optimal location to minimize latency.
# If you are running back-end logic in a Pages Function, running it closer to your back-end infrastructure
# rather than the end user may result in better performance.
# Docs: https://developers.cloudflare.com/pages/functions/smart-placement/#smart-placement
# [placement]
# mode = "smart"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Docs:
# - https://developers.cloudflare.com/pages/functions/bindings/#environment-variables
# Note: Use secrets to store sensitive data.
# - https://developers.cloudflare.com/pages/functions/bindings/#secrets
[vars]
AUTH_SECRET = "KHjom6kJ9yMMh1HZXIETeS1s1oAcm94JzkbgpaWvqLyz9ZiA4xk5PGm+0EI="
AUTH_TRUST_HOST = "true"
GITHUB_CLIENT_ID = "Iv23lizzAv0u3V3m4LME"
GITHUB_CLIENT_SECRET = "542ae24d0c8665b1bea90ab37c2b7785a1227bab"
LEMON_SQUEEZY_API_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5NGQ1OWNlZi1kYmI4LTRlYTUtYjE3OC1kMjU0MGZjZDY5MTkiLCJqdGkiOiI2OGE3NzVhMDIzMDIwNzY4M2QxNGYwZWM4YzRlM2YwZTE5MjRiOTU2MGRjODdlMWVmYjMyZTE2NDlmYTNjMTA3Nzg1ZmUxMmU5MDBmMTJjYiIsImlhdCI6MTcyODE2NTI1OC45MzUyNTUsIm5iZiI6MTcyODE2NTI1OC45MzUyNTgsImV4cCI6MjA0MzY5ODA1OC44OTU5OTksInN1YiI6IjM0MTE5NTEiLCJzY29wZXMiOltdfQ.Dmg8bs5enfKambjWfTFZ0t3o7fFDrXA9b0bvqpxuC8S9CWrqtS8uvs2RGvGOdcZ1ytg57KVVPICox5kG79F1D-ogHBIe1hquY50ebe4NegLzDfsknbHGgxA209PqKA_go89Di9VfESz3hIbaegLzzpdn56Y4IJJ_95GgMiWlOKvwcgZPjUTg_JYawZVRsAjMKsTYQcx77ZjQCDlnsm5cQ4X9a5ifgiZBlUGGzyGm92Q6JVBXT_tHrk9ZcG_c1LZeuJuQ1b6BOAzSsJdJNfon0mlFRLtyofQKC6OehG4B-dKCQcvlF-wZbAODMRGQXmXa1nOKcEU-jN9Z0VjaImZq03P-kSgZSe2-TxRellenDkbS4RBxZ_ASBcU2_nXp4gYLihZqrFfBeSoP9oqmmN4znZytbNylKyPDn8cKD3wxRvEkufRSWzwsk6qmPFIZku0IIaqAhhBlCDbR_jGTpLhvXShMgGyAZI6ZRPLgC1uQug4x3eOmr-R-EVU6mJbTIetv"
LEMON_SQUEEZY_SIGNING_SECRET = "hOQS//kBtPFIMZlW6hANW5sqKQ1EBJ38eD6ji6ciD6/3aVGST9Y7GRNXXNo="
LEMON_SQUEEZY_STORE_ID = "125811"
[[d1_databases]]
binding = "DB"
database_id = "d23e8a5a-a2d7-4092-a556-b9e7c7b421c1"
database_name = "flatcms"
migrations_dir = "drizzle/"

# MY_VARIABLE = "production_value"

# Bind the Workers AI model catalog. Run machine learning models, powered by serverless GPUs, on Cloudflare’s global network
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#workers-ai
# [ai]
# binding = "AI"

# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#d1-databases

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
# [[durable_objects.bindings]]
# name = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"
# script_name = 'my-durable-object'

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#kv-namespaces
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Bind a Queue producer. Use this binding to schedule an arbitrary task that may be processed later by a Queue consumer.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#queue-producers
# [[queues.producers]]
# binding = "MY_QUEUE"
# queue = "my-queue"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#r2-buckets
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# Bind another Worker service. Use this binding to call another Worker without network overhead.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#service-bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"

# To use different bindings for preview and production environments, follow the examples below.
# When using environment-specific overrides for bindings, ALL bindings must be specified on a per-environment basis.
# Docs: https://developers.cloudflare.com/pages/functions/wrangler-configuration#environment-specific-overrides

######## PREVIEW environment config ########

# [env.preview.vars]
# API_KEY = "xyz789"

# [[env.preview.kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "<PREVIEW_NAMESPACE_ID>"

######## PRODUCTION environment config ########

# [env.production.vars]
# API_KEY = "abc123"

# [[env.production.kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "<PRODUCTION_NAMESPACE_ID>"
